config/routes.rb
Rails.application.routes.draw do 

  resource :cart, only: [:show] do
    resources :cart_items, only: [:create, :update, :destroy]
  end

  resources :orders, only: [:new, :create, :show, :index] do
    get 'confirmation', on: :member
  end
  resources :addresses, only: [:new, :create] do
    collection do
      get :states
      get :cities
    end
  end
  
# get 'order_confirmation/:id', to: 'orders#order_confirmation', as: 'order_confirmation'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :courses
  devise_for :users , controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :posts  
  resources :products
  
 
  
  resources :users do
    member do
      post 'follow', to: 'users#follow'
      post 'unfollow', to: 'users#unfollow'
    end
  end
get '/pages/:slug', to: 'cms_pages#show', as: 'cms_page'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
 
  # Defines the root path route ("/")
  root "pages#home"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
     if user.user?
      can :read, Product,  status: 'active'
     elsif user.vendor?
      can :manage, Product
     end
     
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  has_many :orders
  validates :name, :street, :city, :state,  presence: true
  validates :zip, format: { with: /\A\d+\z/, message: "only allows numbers" } , presence: true

  
  def full_address
    "#{name} ,#{street}, #{city},#{zip}, #{state_full},  #{country_full}"
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
         def self.ransackable_attributes(auth_object = nil)
              ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
            end

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

end

app/models/cms_page.rb
class CmsPage < ApplicationRecord
    validates :title, presence: true
    validates :slug, presence: true, uniqueness: true
    validates :description, presence: true
    before_validation :generate_slug, if: -> { title_changed? && slug.blank? }
    extend FriendlyId
    friendly_id :title, use: :slugged
  def generate_slug
    self.slug = title.parameterize
  end

  def to_param
    slug
  end
    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "description", "id", "id_value", "slug", "title", "updated_at"]
      end
      
end

app/models/course.rb
class Course < ApplicationRecord
    validates :name, :description, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  # before_validation :set_total_price
  validates :total_price, presence: true
  belongs_to :user
  has_many :order_items, dependent: :destroy
  belongs_to :address
  enum state: { pending: 0, paid: 1, shipped: 2, cancelled: 3 }
  # accepts_nested_attributes_for :order_items
  def formatted_total_price
    '%.2f' % total_price
  end
 
  private
  # def set_total_price
  #   self.total_price ||= order_items.sum { |item| item.product.price * item.quantity }
  # end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/models/product.rb
class Product < ApplicationRecord
  include ActionView::Helpers::NumberHelper
  validates :name, :description, :price, presence: true
  has_many_attached :images 

  enum status: { active: 'active', inactive: 'inactive' }
  has_many :cart_items
  has_many :order_items

  def formatted_price
    "%.3f" % price
  end

def self.ransackable_attributes(auth_object = nil)
        ["created_at", "description", "id", "id_value", "name", "price", "updated_at"]
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable,
         omniauth_providers: [:google_oauth2,:facebook]
         has_one :cart
         has_many :addresses
         enum role: [:user, :vendor]
         has_many :orders
         validates :first_name, :last_name, :mobile_number, :location, :email, :date_of_birth, presence: true, unless: :omniauth_sign_in?
         followability
         validates :email, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
         message: 'must be a valid email address' }
         validates :mobile_number, uniqueness: true
         def self.from_omniauth(auth)
          puts("********************************")
          name_split = auth.info.name.split(" ")
          puts(auth)
          user = User.where(email: auth.info.email).first
          user ||= User.create!(provider: auth.provider, uid: auth.uid, last_name: name_split[0], first_name: name_split[1], email: auth.info.email, password: Devise.friendly_token[0, 20])
          user
        end
        def omniauth_sign_in?
          provider.present? # Check if the user is signing in via OmniAuth
        end
        def self.ransackable_attributes(auth_object = nil)
          ["avatar_url", "created_at", "date_of_birth", "email", "encrypted_password", "first_name", "full_name", "id", "id_value", "last_name", "location", "mobile_number", "provider", "remember_created_at", "reset_password_sent_at", "reset_password_token", "role", "uid", "updated_at"]
        end
        def unfollow(user)
          followerable_relationships.where(followable_id: user.id).destroy_all
        end
      
end 

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= turbo_include_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload',media: "all" %>  
  </head>
  <body>
    <%= yield %>  
  <%= turbo_include_tags %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/home.html.erb
<%= render partial: 'products/nav' %>
<div class="text-center">
  <% if flash[:alert] %>
    <div class="alert alert-danger">
      <%= flash[:alert] %>
    </div>
  <% end %>

  <% if flash[:notice] %>
    <div class="alert alert-danger">
      <%= flash[:notice] %>
    </div>
  <% end %>
</div>

<div class="container text-end mt-4">
  <%= link_to "Products", products_path, class: "btn btn-primary" %>
</div>


<div class="container text-center mt-4">

  <h1>Pages#home</h1>
  <p class="text-center">Find me in app/views/pages/home.html.erb</p>

  

  <% if current_user %>
    <div>
      <h2>Welcome, <%= current_user.email %></h2>
      <% if current_user.role == 'vendor' %>
        <p>You are logged in as a vendor.</p>
      <% else %>
        <p>You are logged in as a regular user.</p>
      <% end %>
    </div>
  <% end %>

  <% unless current_user.nil? %>
    <table class="table mt-4">
      <thead>
        <tr>
          <th>Email</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% User.where.not(id: current_user.id).each do |user| %>
          <tr>
            <td><%= user.email %></td>
                <td>
                  <% if current_user.following?(user) %>
                    <%= button_to "Unfollow", unfollow_user_path(user) %>
                  <% else %>
                    <%= button_to "Follow", follow_user_path(user) %>
                  <% end %>
                </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/shared/_form.html.erb
<div class="row">
  <div class="col-md-8 mb-4">
    <div class="card mb-4">
      <div class="card-header py-3">
        <h5 class="mb-0">Billing details</h5>
      </div>
      <div class="card-body">
        <%= form_for address, url: addresses_path(product_id: @product&.id), method: :post do |f| %>
         <% if @address.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @address.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row mb-4">
    <div class="col">
      <div class="form-outline">
        <%= f.label :name, "Name", class: "form-label" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="col">
      <div class="form-outline">
        <%= f.label :street, "Street", class: "form-label" %>
        <%= f.text_field :street, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="form-outline mb-4">
    <%= f.label :zip, "ZIP", class: "form-label" %>
    <%= f.text_field :zip, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= f.label :city, "City", class: "form-label" %>
    <%= f.select :city, [], { prompt: "Select a city" }, class: "form-control", id: "address_city",disabled: true  %>
  </div>

  <div class="form-outline mb-4">
    <%= f.label :state, "State", class: "form-label" %>
    <%= f.select :state, [], { prompt: "Select a state" }, class: "form-control", id: "address_state", disabled: true %>
  </div>

  <div class="form-outline mb-4">
    <%= f.label :country, "Country", class: "form-label" %>
    <%= f.select :country, CS.countries.invert, { prompt: "Select a country" }, class: "form-control", id: "address_country" %>
  </div>
<%= f.hidden_field :country_full, id: "address_country_full" %>
  <%= f.hidden_field :state_full, id: "address_state_full" %>
  <%= f.submit "Add Address", class: "btn btn-primary" %>
<% end %>
<%= javascript_include_tag 'addresses' %>