config/routes.rb
Rails.application.routes.draw do 

  resource :cart, only: [:show] do
    resources :cart_items, only: [:create, :update, :destroy]
  end

  resources :orders, only: [:new, :create, :show, :index] do
    get 'confirmation', on: :member
  end
  resources :addresses, only: [:new, :create] do
    collection do
      get :states
      get :cities
    end
  end
  
# get 'order_confirmation/:id', to: 'orders#order_confirmation', as: 'order_confirmation'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :courses
  devise_for :users , controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :posts  
  resources :products
  
 
  
  resources :users do
    member do
      post 'follow', to: 'users#follow'
      post 'unfollow', to: 'users#unfollow'
    end
  end
get '/pages/:slug', to: 'cms_pages#show', as: 'cms_page'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
 
  # Defines the root path route ("/")
  root "pages#home"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
     if user.user?
      can :read, Product,  status: 'active'
     elsif user.vendor?
      can :manage, Product
     end
     
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  has_many :orders
  validates :name, :street, :city, :state,  presence: true
  validates :zip, format: { with: /\A\d+\z/, message: "only allows numbers" } , presence: true

  
  def full_address
    "#{name} ,#{street}, #{city},#{zip}, #{state_full},  #{country_full}"
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
         def self.ransackable_attributes(auth_object = nil)
              ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
            end

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

end

app/models/cms_page.rb
class CmsPage < ApplicationRecord
    validates :title, presence: true
    validates :slug, presence: true, uniqueness: true
    validates :description, presence: true
    before_validation :generate_slug, if: -> { title_changed? && slug.blank? }
    extend FriendlyId
    friendly_id :title, use: :slugged
  def generate_slug
    self.slug = title.parameterize
  end

  def to_param
    slug
  end
    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "description", "id", "id_value", "slug", "title", "updated_at"]
      end
      
end

app/models/course.rb
class Course < ApplicationRecord
    validates :name, :description, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  # before_validation :set_total_price
  validates :total_price, presence: true
  belongs_to :user
  has_many :order_items, dependent: :destroy
  belongs_to :address
  enum state: { pending: 0, paid: 1, shipped: 2, cancelled: 3 }
  # accepts_nested_attributes_for :order_items
  def formatted_total_price
    '%.2f' % total_price
  end
 
  private
  # def set_total_price
  #   self.total_price ||= order_items.sum { |item| item.product.price * item.quantity }
  # end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/models/product.rb
class Product < ApplicationRecord
  include ActionView::Helpers::NumberHelper
  validates :name, :description, :price, presence: true
  has_many_attached :images 

  enum status: { active: 'active', inactive: 'inactive' }
  has_many :cart_items
  has_many :order_items

  def formatted_price
    "%.3f" % price
  end

def self.ransackable_attributes(auth_object = nil)
        ["created_at", "description", "id", "id_value", "name", "price", "updated_at"]
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable,
         omniauth_providers: [:google_oauth2,:facebook]
         has_one :cart
         has_many :addresses
         enum role: [:user, :vendor]
         has_many :orders
         validates :first_name, :last_name, :mobile_number, :location, :email, :date_of_birth, presence: true, unless: :omniauth_sign_in?
         followability
         validates :email, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
         message: 'must be a valid email address' }
         validates :mobile_number, uniqueness: true
         def self.from_omniauth(auth)
          puts("********************************")
          name_split = auth.info.name.split(" ")
          puts(auth)
          user = User.where(email: auth.info.email).first
          user ||= User.create!(provider: auth.provider, uid: auth.uid, last_name: name_split[0], first_name: name_split[1], email: auth.info.email, password: Devise.friendly_token[0, 20])
          user
        end
        def omniauth_sign_in?
          provider.present? # Check if the user is signing in via OmniAuth
        end
        def self.ransackable_attributes(auth_object = nil)
          ["avatar_url", "created_at", "date_of_birth", "email", "encrypted_password", "first_name", "full_name", "id", "id_value", "last_name", "location", "mobile_number", "provider", "remember_created_at", "reset_password_sent_at", "reset_password_token", "role", "uid", "updated_at"]
        end
        def unfollow(user)
          followerable_relationships.where(followable_id: user.id).destroy_all
        end
      
end 

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @cart = current_user.cart || current_user.create_cart
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/cms_pages_helper.rb
module CmsPagesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<%= render 'products/nav' %>

<h1 style="text-align:center;margin-top:15px">Cart</h1>

<% if @cart.cart_items.present? %>
  <div class="row">
    <% total_price = 0 %>
    <% @cart.cart_items.each do |cart_item| %>
      <div class="col-md-4 mb-3">
        <div class="card">
          <div id="carouselExampleSlidesOnly<%= cart_item.id %>" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <% cart_item.product.images.each_with_index do |image, index| %>
                <div class="carousel-item <%= "active" if index == 0 %>">
                  <%= link_to product_path(cart_item.product) do %>
                    <%= image_tag image, class: "d-block w-100", style: "height: 350px;" %>
                  <% end %>
                </div>
              <% end %>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleSlidesOnly<%= cart_item.id %>" type="button" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleSlidesOnly<%= cart_item.id %>" type="button" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
            </a>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= cart_item.product.name %></h5>
            <p class="card-text"><%= cart_item.product.description %></p>
            <div class="input-group mb-3">
              <%= form_with(url: cart_cart_item_path(cart_item), method: :patch) do |form| %>
                <%= form.number_field :quantity, value: cart_item.quantity, class: "form-control mr-2" %>
                <div class="input-group-append">
                  <%= form.submit "Update", class: "btn btn-outline-secondary mt-2" %>
                </div>
              <% end %>
            </div>
            <p class="card-text">Price: <%= number_to_currency(cart_item.product.price) %> for each</p>
            <p class="card-text">Price: <%= number_to_currency(cart_item.product.price * cart_item.quantity) %></p>
            <% total_price += cart_item.product.price * cart_item.quantity %>
            <%= button_to 'Remove', cart_cart_item_path(cart_item), method: :delete, data: { turbo: "false" }, class: "btn btn-danger" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-12 text-center">
      <h5>Total Price: <%= number_to_currency(total_price) %></h5>
      <%= link_to 'Checkout', new_order_path, class: "btn btn-primary" %>
    </div>
  </div>
<% else %>
  <div class="alert alert-info" role="alert">
    Your cart is empty.
  </div>
<% end %>