config/routes.rb
Rails.application.routes.draw do 

  resource :cart, only: [:show] do
    resources :cart_items, only: [:create, :update, :destroy]
  end

  resources :orders, only: [:new, :create, :show, :index] do
    get 'confirmation', on: :member
  end
  resources :addresses, only: [:new, :create] do
    collection do
      get :states
      get :cities
    end
  end
  
# get 'order_confirmation/:id', to: 'orders#order_confirmation', as: 'order_confirmation'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :courses
  devise_for :users , controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :posts  
  resources :products
  
 
  
  resources :users do
    member do
      post 'follow', to: 'users#follow'
      post 'unfollow', to: 'users#unfollow'
    end
  end
get '/pages/:slug', to: 'cms_pages#show', as: 'cms_page'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
 
  # Defines the root path route ("/")
  root "pages#home"
end

app/models/product.rb
class Product < ApplicationRecord
  include ActionView::Helpers::NumberHelper
  validates :name, :description, :price, presence: true
  has_many_attached :images 

  enum status: { active: 'active', inactive: 'inactive' }
  has_many :cart_items
  has_many :order_items

  def formatted_price
    "%.3f" % price
  end

def self.ransackable_attributes(auth_object = nil)
        ["created_at", "description", "id", "id_value", "name", "price", "updated_at"]
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user!
   
    load_and_authorize_resource
    def index
      @products = Product.where(status: 'active')
    end
  
    def show
      @product = Product.find(params[:id])
    end
    def new
      @product = Product.new
    end
    
    def create
      @product = Product.new(product_params)
      @product.status = "active"
      respond_to do |format|
        if @product.save
          format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
          format.json { render :show, status: :created, location: @product }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end
    def edit
      @product = Product.find(params[:id])
    end
  
    def update
      respond_to do |format|
        if @product.update(product_params)
          format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
          format.json { render :show, status: :ok, location: @product }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end
    def show_custom
      @products = Product.where(status: 'active')
      render 'custom_show'
    end
    
  
    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      respond_to do |format|
        format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
        format.json { head :no_content }
      end
    end
    
    private
    def set_product
      @product = Product.find(params[:id])
    end
  
    def product_params
      params.require(:product).permit(:name, :description, :price, images: [])
    end
  end
  

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">

      <%= form_for @product do |f| %>
        <% if @product.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
            <ul>
              <% @product.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="mb-3">
          <%= f.label :name, class: "form-label" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :description, class: "form-label" %>
          <%= f.text_area :description, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :price, class: "form-label" %>
          <%= f.number_field :price, class: "form-control" %>
        </div>
        <div class="mb-3">
         <%= f.label "Images", class: "form-label" %>
          <%= f.file_field :images, multiple: true, class: "form-control" %>
        </div>

        <div class="actions">
          <%= f.submit @product.new_record? ? 'Create' : 'Update', class: "btn btn-primary" %>
          <%= link_to "Back", products_path, class: "btn btn-secondary ms-2" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Home", root_path, class: "navbar-brand  mb-0 h1" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if current_user %>
          <li class="nav-item me-2 " >
            <%= link_to "Cart", cart_path, class: "btn btn-success  m-4 "%>
          </li>
          <li class="nav-item me-2">
            <%= link_to "Orders", orders_path, class: "btn btn-primary m-4" %>
          </li>
            <li class="nav-item">
              <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-danger mt-4", data: { turbo: "false" } %>
            </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Create Account", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/products/custom_show.html.erb
<%= render 'nav' %>
<h1 style="text-align: center; margin-top: 20px;">Products</h1>

<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-4">
      <div class="card">
        <div class="bg-image hover-overlay" data-mdb-ripple-init data-mdb-ripple-color="light">
          <%= link_to product_path(product) do %>
            <%= image_tag product.image, class: "img-fluid" %>
            <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
          <% end %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= product.name %></h5>
          <p class="card-text"><%= product.description %></p>
          <p class="card-text"><strong>Price:</strong> <%= product.price %></p>
          <% if can? :edit, product %>
            <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-primary btn-sm' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<% if can? :create, Product %>
  <%= link_to 'New Product', new_product_path, class: 'btn btn-success' %>
<% end %>

app/views/products/edit.html.erb
<h1 style="text-align:center; margin-top:20px">Edit Product</h1>

<%= render 'form', product: @product %>

app/views/products/index.html.erb
<%= render 'nav' %>
<h1 style="text-align: center; margin-top: 20px;">Products</h1>

<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-4">
      <div class="card">
        <div id="carouselExampleControls<%= product.id %>" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner">
            <% product.images.each_with_index do |image, index| %>
              <div class="carousel-item <%= "active" if index == 0 %>">
                <%= link_to product_path(product) do %>
                  <%= image_tag image, class: "d-block w-100" %>
                <% end %>
              </div>
            <% end %>
          </div>
          <button class="carousel-control-prev" type="button" href="#carouselExampleControls<%= product.id %>" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" href="#carouselExampleControls<%= product.id %>" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= product.name %></h5>
          <p class="card-text"><%= product.description %></p>
          <p class="card-text"><strong>Price:</strong> <%= product.price %></p>
          <% if can? :edit, product %>
            <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-primary btn-sm' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<% if can? :create, Product %>
  <%= link_to 'New Product', new_product_path, class: 'btn btn-success' %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

app/views/products/show.html.erb
<%= render 'nav' %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="mb-4"><%= @product.name %></h1>
      <div>
        <% if @product.active? %>
          <% @product.images.each do |image| %>
            <%= image_tag image, style: "width:200px;" %>
          <% end %>
          <p><strong>Description:</strong> <%= @product.description %></p>
          <p><strong>Price:</strong> <%= @product.price %></p>
        <% end %>
        <div class="justify-content">
          <%= button_to 'Add to Cart', cart_cart_items_path(product_id: @product.id), method: :post, class: 'btn btn-primary mr-3' %>
          <%= link_to 'Buy Now', new_order_path(product_id: @product.id), class: 'btn btn-success  mb-3 ' %>
        </div>
        <% if can? :edit, @product %>
          <%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-primary btn-sm' %>
        <% end %>
        <%= link_to 'Back', products_path, class: "btn btn-secondary ms-2" %>
      </div>
    </div>
  </div>
</div>